### PR TITLE
v1.0.14 release -- version.go updated

### PR DESCRIPTION
**Pull request by garymm**

### CODE REVIEW

**Comment by rcoreilly** [comment]
I'm not sure this works as a PR?  It needs to add a git tag in the process..

**Comment by rcoreilly** [comment]
My workflow is to update the Makefile version number, then run 'make release', in the master branch.  I can do that or you could if you want -- lmk.

**Comment by garymm** [comment]
Yeah I don't have permissions to push the tag, but I think they can technically be done separately. In any case feel free to close this and do it all yourself.

**Comment by garymm** [comment]
Done in https://github.com/emer/empi/commit/19446db93350158e67b8e0eda410f0b77f87a3e5

**Pull request closed without merging**
