### PR TITLE
fix bazel

### PR DESCRIPTION
**Pull request by garymm**

### CODE REVIEW

**Comment by rcoreilly** [comment]
Is there a way to get bazel to just use the go build directly?  as far as I can tell, it is entirely superfluous and, worse, and additional maintenance pain obviously..

**Comment by garymm** [comment]
I wrote a doc several months ago about why I think Bazel is valuable. Just because you don't use it doesn't mean it's entirely superfluous.

**Comment by rcoreilly** [comment]
To be clear: I'm not saying "no Bazel" but rather: "Bazel calls go" -- surely this must be possible?  It just doesn't make sense for a pure go package with no external dependencies to require redundant updating, right?

**Comment by garymm** [comment]
In most cases explicitly writing and maintaining the bazel BUILD files isn't necessary, it can figure them out from go. But in this case I think it got confused by the circular dependencies between empi and emer.

**Comment by rcoreilly** [comment]
Ok so can we remove all the BUILD files then, and just have bazel figure them out from go?

**Comment by garymm** [comment]
If there are no dependency cycles then I think we should be able to remove most of the BUILD.bazel files.

**Comment by rcoreilly** [comment]
Go doesn't allow dependency cycles in the first place, so that should be the case!  Can you go ahead and do the PR's for that?

**Comment by garymm** [comment]
Seems the cyclic dep was removed in https://github.com/emer/empi/commit/df8777b76e1506f097f636bf6ed43ea51066d98d

Removed bazel files from this repo:
https://github.com/emer/empi/pull/4

**Pull request merged**
